/**
 * Planilla Fauna Darwin Core del SEA.
 *
 * No es una plantilla más: es la que el Servicio de Evaluación Ambiental exige
 * como Anexo 1 de los "Criterios Técnicos para Campañas de Terreno de Fauna
 * Terrestre y Validación de Datos" (Res. Ex. 202299101888, 10 nov 2022), en
 * formato XLSX y como parte de la caracterización de línea base.
 *
 * Son 170 columnas Darwin Core, en el orden exacto del anexo oficial. Las que
 * ProTerr no puede llenar quedan VACÍAS a propósito: una columna en blanco se
 * completa en gabinete, una columna inventada pasa a un informe.
 *
 * Los nombres de columna son términos del estándar Darwin Core y de una norma
 * pública de uso obligatorio; no son el formulario privado de ninguna empresa.
 */
import type { ExportTemplate, TemplateColumn } from './template';

function col(header: string, extra: Partial<TemplateColumn> = {}): TemplateColumn {
  return { header, fieldId: extra.fieldId ?? null, ...(extra.constant ? { constant: extra.constant } : {}) };
}

export const SEA_DWC_TEMPLATE: ExportTemplate = {
  id: 'sea-fauna-darwin-core',
  name: 'SEA — Planilla Fauna Darwin Core',
  organization: 'Servicio de Evaluación Ambiental (Chile)',
  description: 'Anexo 1 del criterio de evaluación del SEIA para campañas de terreno de fauna terrestre. 170 columnas Darwin Core, en el orden oficial.',
  createdAt: '2022-11-10T00:00:00Z',
  sourceFileName: 'anexo_1._planilla_fauna_darwin_core.xlsx',
  sheets: [{
    name: 'Planilla',
    scope: 'registros_todos',
    columns: [
    col('occurrenceID', { fieldId: 'trace.occurrenceId' }),
    col('basisOfRecord', { constant: 'HumanObservation' }),
    col('institutionCode', { fieldId: 'project.client' }),
    col('collectionCode'),
    col('catalogNumber'),
    col('type', { constant: 'Event' }),
    col('modified', { fieldId: 'trace.createdAt' }),
    col('language', { constant: 'es' }),
    col('license'),
    col('rightsHolder'),
    col('accessRights'),
    col('bibliographicCitation'),
    col('references'),
    col('institutionID'),
    col('collectionID'),
    col('datasetID'),
    col('datasetName', { fieldId: 'project.name' }),
    col('ownerInstitutionCode', { fieldId: 'project.client' }),
    col('informationWithheld', { fieldId: 'conservation.origin' }),
    col('dataGeneralizations'),
    col('dynamicProperties', { fieldId: 'conservation.category' }),
    col('occurrenceRemarks', { fieldId: 'occurrence.notes' }),
    col('recordNumber', { fieldId: 'occurrence.site' }),
    col('recordedBy', { fieldId: 'event.recordedBy' }),
    col('organismID', { fieldId: 'occurrence.organismId' }),
    col('individualCount', { fieldId: 'occurrence.count' }),
    col('organismQuantity', { fieldId: 'occurrence.count' }),
    col('organismQuantityType', { constant: 'Individuos' }),
    col('organismName'),
    col('organismScope'),
    col('associatedOrganisms'),
    col('organismRemarks'),
    col('sex', { fieldId: 'occurrence.sex' }),
    col('lifeStage', { fieldId: 'occurrence.lifeStage' }),
    col('reproductiveCondition', { fieldId: 'occurrence.reproductiveCondition' }),
    col('behavior', { fieldId: 'occurrence.behaviour' }),
    col('establishmentMeans'),
    col('occurrenceStatus', { constant: 'Presente' }),
    col('preparations'),
    col('disposition'),
    col('otherCatalogNumbers'),
    col('previousIdentifications'),
    col('associatedMedia', { fieldId: 'occurrence.photos' }),
    col('associatedReferences'),
    col('associatedOccurrences'),
    col('associatedSequences'),
    col('associatedTaxa'),
    col('materialSampleID'),
    col('parentEventID'),
    col('eventID', { fieldId: 'event.id' }),
    col('samplingProtocol', { fieldId: 'event.method' }),
    col('sampleSizeValue', { fieldId: 'effort.distance' }),
    col('sampleSizeUnit', { constant: 'metros' }),
    col('samplingEffort', { fieldId: 'effort.label' }),
    col('eventDate', { fieldId: 'event.date' }),
    col('eventTime', { fieldId: 'occurrence.time' }),
    col('startDayOfYear'),
    col('endDayOfYear'),
    col('year', { fieldId: 'event.year' }),
    col('month', { fieldId: 'event.month' }),
    col('day', { fieldId: 'event.day' }),
    col('verbatimEventDate', { fieldId: 'event.date' }),
    col('habitat', { fieldId: 'station.habitat' }),
    col('fieldNumber', { fieldId: 'occurrence.trapNumber' }),
    col('fieldNotes', { fieldId: 'event.notes' }),
    col('eventRemarks', { fieldId: 'event.notes' }),
    col('locationID', { fieldId: 'station.code' }),
    col('higherGeographyID'),
    col('higherGeography'),
    col('continent', { constant: 'South America' }),
    col('waterBody'),
    col('islandGroup'),
    col('island'),
    col('country', { constant: 'Chile' }),
    col('countryCode', { constant: 'CL' }),
    col('stateProvince', { fieldId: 'station.region' }),
    col('county'),
    col('municipality'),
    col('locality', { fieldId: 'station.sector' }),
    col('verbatimLocality'),
    col('verbatimElevation'),
    col('minimumElevationInMeters'),
    col('maximumElevationInMeters'),
    col('verbatimDepth'),
    col('minimumDepthInMeters'),
    col('maximumDepthInMeters'),
    col('minimumDistanceAboveSurfaceInMeters'),
    col('maximumDistanceAboveSurfaceInMeters'),
    col('locationAccordingTo'),
    col('locationRemarks', { fieldId: 'station.slope' }),
    col('verbatimCoordinates'),
    col('verbatimLatitude', { fieldId: 'occurrence.utmNorth' }),
    col('verbatimLongitude', { fieldId: 'occurrence.utmEast' }),
    col('verbatimCoordinateSystem', { constant: 'UTM' }),
    col('verbatimSRS', { constant: 'WGS84' }),
    col('decimalLatitude', { fieldId: 'occurrence.latitude' }),
    col('decimalLongitude', { fieldId: 'occurrence.longitude' }),
    col('geodeticDatum', { constant: 'WGS84' }),
    col('coordinateUncertaintyInMeters'),
    col('coordinatePrecision'),
    col('pointRadiusSpatialFit'),
    col('footprintWKT'),
    col('footprintSRS'),
    col('footprintSpatialFit'),
    col('georeferencedBy'),
    col('georeferencedDate'),
    col('georeferenceProtocol'),
    col('georeferenceSources'),
    col('georeferenceVerificationStatus'),
    col('georeferenceRemarks'),
    col('geologicalContextID'),
    col('earliestEonOrLowestEonothem'),
    col('latestEonOrHighestEonothem'),
    col('earliestEraOrLowestErathem'),
    col('latestEraOrHighestErathem'),
    col('earliestPeriodOrLowestSystem'),
    col('latestPeriodOrHighestSystem'),
    col('earliestEpochOrLowestSeries'),
    col('latestEpochOrHighestSeries'),
    col('earliestAgeOrLowestStage'),
    col('latestAgeOrHighestStage'),
    col('lowestBiostratigraphicZone'),
    col('highestBiostratigraphicZone'),
    col('lithostratigraphicTerms'),
    col('group'),
    col('formation'),
    col('member'),
    col('bed'),
    col('identificationID'),
    col('identifiedBy', { fieldId: 'event.identifiedBy' }),
    col('dateIdentified'),
    col('identificationReferences'),
    col('identificationVerificationStatus'),
    col('identificationRemarks'),
    col('identificationQualifier', { fieldId: 'occurrence.confidence' }),
    col('typeStatus'),
    col('taxonID'),
    col('scientificNameID'),
    col('acceptedNameUsageID'),
    col('parentNameUsageID'),
    col('originalNameUsageID'),
    col('nameAccordingToID'),
    col('namePublishedInID'),
    col('taxonConceptID'),
    col('scientificName', { fieldId: 'taxon.scientificName' }),
    col('acceptedNameUsage'),
    col('parentNameUsage'),
    col('originalNameUsage'),
    col('nameAccordingTo'),
    col('namePublishedIn'),
    col('namePublishedInYear'),
    col('higherClassification'),
    col('kingdom', { fieldId: 'taxon.kingdom' }),
    col('phylum', { fieldId: 'taxon.phylum' }),
    col('class', { fieldId: 'taxon.class' }),
    col('order', { fieldId: 'taxon.order' }),
    col('family', { fieldId: 'taxon.family' }),
    col('genus', { fieldId: 'taxon.genus' }),
    col('subgenus'),
    col('specificEpithet', { fieldId: 'taxon.specificEpithet' }),
    col('infraspecificEpithet', { fieldId: 'taxon.infraspecificEpithet' }),
    col('taxonRank', { constant: 'species' }),
    col('verbatimTaxonRank'),
    col('scientificNameAuthorship'),
    col('vernacularName', { fieldId: 'occurrence.commonName' }),
    col('nomenclaturalCode', { constant: 'ICZN' }),
    col('taxonomicStatus'),
    col('nomenclaturalStatus'),
    col('taxonRemarks'),
    col('expedition', { fieldId: 'campaign.name' }),
    ],
  }],
};
